### ISSUE TITLE
Add Branch Protection for Master Branch

### ISSUE THREAD

**Issue by ketdougi** [realjaidhaliwal/game-of-life-modern-java#6] opened 2022-02-24 03:45 UTC
Branch protection for master branch must be setup in settings

**Comment by ketdougi** [comment] 2022-02-24 04:13
I can't access "Settings" so I cannot add the branch protection

**Comment by OwenBC** [comment] 2022-02-24 05:12
Duplicate of #5

**Closed as completed by OwenBC** 2022-02-24 05:12 UTC
